services:
  postgres:
    container_name:
      pstgres_medsystem

    image: postgres:18-alpine

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: med_system