spring:
  application:
    name: AsMoney


  datasource:
    url: jdbc:postgresql://localhost:5432/med_system
    username: admin
    password: docker
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true

  jwt :
    SECRET_KEY : "#?wDco~ONPTM;$@P))KbO3O7Ft[tH"
